/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoraswing;

/**
 *
 * @author josemaria
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    private static TypeCalculation typeCalculation;
    private static boolean toCalculate = false;
    private static double numberOfCalculation = 0;
    private static double firstNumber;
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlPantalla = new javax.swing.JLabel();
        jbBotonCero = new javax.swing.JButton();
        jbBotonUno = new javax.swing.JButton();
        jbBotonComa = new javax.swing.JButton();
        jbBotonIgual = new javax.swing.JButton();
        jbBotonDos = new javax.swing.JButton();
        jbBotonTres = new javax.swing.JButton();
        jbBotonCuatro = new javax.swing.JButton();
        jbBotonCinco = new javax.swing.JButton();
        jbBotonSeis = new javax.swing.JButton();
        jbBotonSiete = new javax.swing.JButton();
        jbBotonOcho = new javax.swing.JButton();
        jbBotonNueve = new javax.swing.JButton();
        jbBotonDividir = new javax.swing.JButton();
        jbBotonMultiplicar = new javax.swing.JButton();
        jbBotonSumar = new javax.swing.JButton();
        jbBotonRestar = new javax.swing.JButton();
        jbBotonBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlPantalla.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jlPantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlPantalla.setText("0");

        jbBotonCero.setText("0");
        jbBotonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonCeroActionPerformed(evt);
            }
        });

        jbBotonUno.setText("1");
        jbBotonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonUnoActionPerformed(evt);
            }
        });

        jbBotonComa.setText(",");
        jbBotonComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonComaActionPerformed(evt);
            }
        });

        jbBotonIgual.setText("=");
        jbBotonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonIgualActionPerformed(evt);
            }
        });

        jbBotonDos.setText("2");
        jbBotonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonDosActionPerformed(evt);
            }
        });

        jbBotonTres.setText("3");
        jbBotonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonTresActionPerformed(evt);
            }
        });

        jbBotonCuatro.setText("4");
        jbBotonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonCuatroActionPerformed(evt);
            }
        });

        jbBotonCinco.setText("5");
        jbBotonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonCincoActionPerformed(evt);
            }
        });

        jbBotonSeis.setText("6");
        jbBotonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonSeisActionPerformed(evt);
            }
        });

        jbBotonSiete.setText("7");
        jbBotonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonSieteActionPerformed(evt);
            }
        });

        jbBotonOcho.setText("8");
        jbBotonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonOchoActionPerformed(evt);
            }
        });

        jbBotonNueve.setText("9");
        jbBotonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonNueveActionPerformed(evt);
            }
        });

        jbBotonDividir.setText("/");
        jbBotonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonDividirActionPerformed(evt);
            }
        });

        jbBotonMultiplicar.setText("x");
        jbBotonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonMultiplicarActionPerformed(evt);
            }
        });

        jbBotonSumar.setText("+");
        jbBotonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonSumarActionPerformed(evt);
            }
        });

        jbBotonRestar.setText("-");
        jbBotonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonRestarActionPerformed(evt);
            }
        });

        jbBotonBorrar.setText("C");
        jbBotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBotonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbBotonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jbBotonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbBotonTres, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jbBotonComa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jbBotonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBotonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jbBotonBorrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jbBotonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jbBotonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbBotonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbBotonNueve, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(jbBotonSeis, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbBotonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBotonRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBotonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBotonSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBotonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jlPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbBotonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBotonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbBotonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbBotonSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbBotonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBotonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBotonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbBotonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBotonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBotonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBotonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBotonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBotonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBotonRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBotonCero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBotonComa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBotonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBotonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonCeroActionPerformed
        añadirNumeroALaPantalla(0);
    }//GEN-LAST:event_jbBotonCeroActionPerformed

    private void jbBotonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonSieteActionPerformed
        añadirNumeroALaPantalla(7);
    }//GEN-LAST:event_jbBotonSieteActionPerformed

    private void jbBotonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonUnoActionPerformed
        añadirNumeroALaPantalla(1);
    }//GEN-LAST:event_jbBotonUnoActionPerformed

    private void jbBotonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonSumarActionPerformed
        setTypeCalculation(TypeCalculation.ADDITION);
    }//GEN-LAST:event_jbBotonSumarActionPerformed

    private void jbBotonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonDosActionPerformed
        añadirNumeroALaPantalla(2);
    }//GEN-LAST:event_jbBotonDosActionPerformed

    private void jbBotonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonNueveActionPerformed
        añadirNumeroALaPantalla(9);
    }//GEN-LAST:event_jbBotonNueveActionPerformed

    private void jbBotonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonOchoActionPerformed
        añadirNumeroALaPantalla(8);
    }//GEN-LAST:event_jbBotonOchoActionPerformed

    private void jbBotonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonSeisActionPerformed
        añadirNumeroALaPantalla(6);
    }//GEN-LAST:event_jbBotonSeisActionPerformed

    private void jbBotonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonCincoActionPerformed
        añadirNumeroALaPantalla(5);
    }//GEN-LAST:event_jbBotonCincoActionPerformed

    private void jbBotonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonDividirActionPerformed
        setTypeCalculation(TypeCalculation.DIVISION);
    }//GEN-LAST:event_jbBotonDividirActionPerformed

    private void jbBotonComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonComaActionPerformed
        añadirComaALaPantalla();
    }//GEN-LAST:event_jbBotonComaActionPerformed

    private void jbBotonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonMultiplicarActionPerformed
        setTypeCalculation(TypeCalculation.MULTIPLICATION);
    }//GEN-LAST:event_jbBotonMultiplicarActionPerformed

    private void jbBotonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonIgualActionPerformed
        double result = 0;
        double secondNumber = Double.parseDouble(jlPantalla.getText().replace(',', '.'));
        switch (typeCalculation) {
            case ADDITION -> result = firstNumber + secondNumber;
            case DIVISION -> result = firstNumber / secondNumber;
            case MULTIPLICATION -> result = firstNumber * secondNumber;
            case SUBTRACTION -> result = firstNumber - secondNumber;
        }
        toCalculate = true;
        añadirNumeroALaPantalla(result);
    }//GEN-LAST:event_jbBotonIgualActionPerformed

    private void jbBotonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonTresActionPerformed
        añadirNumeroALaPantalla(3);
    }//GEN-LAST:event_jbBotonTresActionPerformed

    private void jbBotonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonCuatroActionPerformed
        añadirNumeroALaPantalla(4);
    }//GEN-LAST:event_jbBotonCuatroActionPerformed

    private void jbBotonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonRestarActionPerformed
        setTypeCalculation(TypeCalculation.SUBTRACTION);
    }//GEN-LAST:event_jbBotonRestarActionPerformed

    private void jbBotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBotonBorrarActionPerformed
        // TODO add your handling code here:
        jlPantalla.setText("0");
    }//GEN-LAST:event_jbBotonBorrarActionPerformed

    private void añadirNumeroALaPantalla (double numero) {
        String pantallaContent = jlPantalla.getText().replace(',', '.');
        double numeroPantalla = Double.parseDouble(pantallaContent);
        if (!pantallaContent.startsWith("0.") && pantallaContent.startsWith("0") || toCalculate) {
            double parteDecimal = numero % 1;
            if (parteDecimal == 0.0) {
                jlPantalla.setText("" + (int)numero); 
            } else{
                jlPantalla.setText("" + Math.round(numero * 100.0) / 100.0);
            }
            toCalculate = false;
        } else if (pantallaContent.length() < 9) {
            double parteDecimal = numeroPantalla % 1;
            if (parteDecimal == 0.0) {
                jlPantalla.setText(jlPantalla.getText() + (int)numero);
            } else {
                numeroPantalla += numero;
                jlPantalla.setText(""+Math.round(numeroPantalla * 100.0) / 100.0);
            }
        }
    }
    
    private void añadirComaALaPantalla () {
        String contenidoPantalla = jlPantalla.getText();
        if (!contenidoPantalla.endsWith(",")) {
            contenidoPantalla += ",";
            jlPantalla.setText(contenidoPantalla);
        }
    }
    
    private void setTypeCalculation(TypeCalculation newTypeCalculation) {
        typeCalculation = newTypeCalculation;
        String contendioPantalla = jlPantalla.getText().replace(',', '.');
        firstNumber = Double.parseDouble(contendioPantalla);
        toCalculate = true;
    }
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbBotonBorrar;
    private javax.swing.JButton jbBotonCero;
    private javax.swing.JButton jbBotonCinco;
    private javax.swing.JButton jbBotonComa;
    private javax.swing.JButton jbBotonCuatro;
    private javax.swing.JButton jbBotonDividir;
    private javax.swing.JButton jbBotonDos;
    private javax.swing.JButton jbBotonIgual;
    private javax.swing.JButton jbBotonMultiplicar;
    private javax.swing.JButton jbBotonNueve;
    private javax.swing.JButton jbBotonOcho;
    private javax.swing.JButton jbBotonRestar;
    private javax.swing.JButton jbBotonSeis;
    private javax.swing.JButton jbBotonSiete;
    private javax.swing.JButton jbBotonSumar;
    private javax.swing.JButton jbBotonTres;
    private javax.swing.JButton jbBotonUno;
    private javax.swing.JLabel jlPantalla;
    // End of variables declaration//GEN-END:variables
}
