
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Movimiento;
import modelo.TarjetaCredito;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author josemaria
 */
public class JDTarjeta extends javax.swing.JDialog {
    TarjetaCredito tarjetaCredito;
    /**
     * Creates new form JDTarjeta
     */
    public JDTarjeta(java.awt.Frame parent, boolean modal, TarjetaCredito tarjetaCredito) {
        super(parent, modal);
        initComponents();
        this.tarjetaCredito = tarjetaCredito;
        inicializar();
    }
    private void inicializar() {
        jlTitular.setText(tarjetaCredito.getTitular());
        jlNIF.setText(tarjetaCredito.getNif());
        jlPIN.setText(tarjetaCredito.getPin());
        jlLimite.setText(String.valueOf(tarjetaCredito.getLimite()));
        jlNumeroTarjeta.setText(tarjetaCredito.getNumeroTarjeta());
        jlCaducidad.setText(tarjetaCredito.getMesCaducidad()+"/"+tarjetaCredito.getAñoCaducidad());
        actualizarGastoTotal();
    }
    
    public boolean añadirMovimiento(String concepto, double cantidad) {
        return tarjetaCredito.pagar(cantidad, concepto);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlTituloTitular = new javax.swing.JLabel();
        jlTituloNIF = new javax.swing.JLabel();
        jlTituloPIN = new javax.swing.JLabel();
        jlTituloNumeroTarjeta = new javax.swing.JLabel();
        jlTitular = new javax.swing.JLabel();
        jlNIF = new javax.swing.JLabel();
        jlPIN = new javax.swing.JLabel();
        jlTituloLimite = new javax.swing.JLabel();
        jlLimite = new javax.swing.JLabel();
        jlNumeroTarjeta = new javax.swing.JLabel();
        jlTituloCaducidad = new javax.swing.JLabel();
        jlCaducidad = new javax.swing.JLabel();
        jlTituloGastoTotal = new javax.swing.JLabel();
        jbRealizarPago = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jlGastoTotal = new javax.swing.JLabel();
        jbVisualizarPagos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlTitulo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jlTitulo.setText("TARJETA");

        jlTituloTitular.setText("Titular: ");

        jlTituloNIF.setText("NIF: ");

        jlTituloPIN.setText("PIN:");

        jlTituloNumeroTarjeta.setText("Numero Tarjeta:");

        jlTitular.setText(" ");

        jlNIF.setText(" ");

        jlPIN.setText(" ");

        jlTituloLimite.setText("Limite:");

        jlLimite.setText(" ");

        jlTituloCaducidad.setText("Caducidad:");

        jlCaducidad.setText(" ");

        jlTituloGastoTotal.setText("Gasto Total:");

        jbRealizarPago.setText("Realizar Pago");
        jbRealizarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRealizarPagoActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jlGastoTotal.setText(" ");

        jbVisualizarPagos.setText("Visualizar Pagos");
        jbVisualizarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisualizarPagosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalir)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jlTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlTituloTitular)
                                    .addComponent(jlTituloNIF)
                                    .addComponent(jlTituloPIN)
                                    .addComponent(jlTituloLimite)
                                    .addComponent(jlTituloNumeroTarjeta)
                                    .addComponent(jlTituloCaducidad)
                                    .addComponent(jlTituloGastoTotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlTitular)
                                    .addComponent(jlNIF)
                                    .addComponent(jlPIN)
                                    .addComponent(jlLimite)
                                    .addComponent(jlCaducidad)
                                    .addComponent(jlNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlGastoTotal)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jbRealizarPago)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbVisualizarPagos)))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlTitulo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTituloTitular)
                    .addComponent(jlTitular))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTituloNIF)
                    .addComponent(jlNIF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTituloPIN)
                    .addComponent(jlPIN))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTituloLimite)
                    .addComponent(jlLimite))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTituloNumeroTarjeta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTituloCaducidad)
                    .addComponent(jlCaducidad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTituloGastoTotal)
                    .addComponent(jlGastoTotal))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir)
                    .addComponent(jbRealizarPago)
                    .addComponent(jbVisualizarPagos))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbRealizarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRealizarPagoActionPerformed
        JDRealizarPago jDRealizarPago = new JDRealizarPago(this,true,tarjetaCredito);
        jDRealizarPago.setVisible(true);
        
        if (jDRealizarPago.isPagoRealizado()) {
            actualizarGastoTotal();
        }
    }//GEN-LAST:event_jbRealizarPagoActionPerformed

    private void jbVisualizarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisualizarPagosActionPerformed
        JDMovimientos jDMovimientos = new JDMovimientos(this, true);
        int numeroTotalMovimientos = tarjetaCredito.numeroMovimientos();
        if (numeroTotalMovimientos == 0) {
            JOptionPane.showMessageDialog(this, "La tarjeta no posee Movimientos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            ArrayList<Movimiento> movimientos = tarjetaCredito.movimientos(numeroTotalMovimientos);
            movimientos.forEach(movimiento -> jDMovimientos.añadirMovimiento(movimiento));
            jDMovimientos.setVisible(true);
        }
    }//GEN-LAST:event_jbVisualizarPagosActionPerformed

    private void actualizarGastoTotal() {
        jlGastoTotal.setText(String.valueOf(tarjetaCredito.gastado()));
    }
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDTarjeta dialog = new JDTarjeta(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbRealizarPago;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbVisualizarPagos;
    private javax.swing.JLabel jlCaducidad;
    private javax.swing.JLabel jlGastoTotal;
    private javax.swing.JLabel jlLimite;
    private javax.swing.JLabel jlNIF;
    private javax.swing.JLabel jlNumeroTarjeta;
    private javax.swing.JLabel jlPIN;
    private javax.swing.JLabel jlTitular;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlTituloCaducidad;
    private javax.swing.JLabel jlTituloGastoTotal;
    private javax.swing.JLabel jlTituloLimite;
    private javax.swing.JLabel jlTituloNIF;
    private javax.swing.JLabel jlTituloNumeroTarjeta;
    private javax.swing.JLabel jlTituloPIN;
    private javax.swing.JLabel jlTituloTitular;
    // End of variables declaration//GEN-END:variables
}
