/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author josemaria
 */
public class JFMenu extends javax.swing.JFrame {
    private static int numeroTarjetasExistentes = 0;

    /**
     * Creates new form JFMenu
     */
    public JFMenu() {
        initComponents();
        inicializar();
    }
    
    private void inicializar() {
        jbModificarTarjeta.setVisible(false);
        jbEliminarTarjeta.setVisible(false);
        jlTotalGastado.setVisible(false);
        jlTarjetasExistentes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlBienvenida = new javax.swing.JLabel();
        jbAñadirTarjeta = new javax.swing.JButton();
        jbModificarTarjeta = new javax.swing.JButton();
        jbEliminarTarjeta = new javax.swing.JButton();
        jlTotalGastado = new javax.swing.JLabel();
        jlTarjetasExistentes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlBienvenida.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jlBienvenida.setText("GESTION DE TARJETAS");

        jbAñadirTarjeta.setText("Crear Nueva");
        jbAñadirTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAñadirTarjetaActionPerformed(evt);
            }
        });

        jbModificarTarjeta.setText("Modificar Tarjeta");
        jbModificarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarTarjetaActionPerformed(evt);
            }
        });

        jbEliminarTarjeta.setText("Eliminar Tarjeta");
        jbEliminarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarTarjetaActionPerformed(evt);
            }
        });

        jlTotalGastado.setText("Total Gastado");

        jlTarjetasExistentes.setText("Tarjetas Existentes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbModificarTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbAñadirTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbEliminarTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jlBienvenida)))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTotalGastado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlTarjetasExistentes, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlBienvenida)
                .addGap(50, 50, 50)
                .addComponent(jbAñadirTarjeta)
                .addGap(4, 4, 4)
                .addComponent(jlTotalGastado)
                .addGap(8, 8, 8)
                .addComponent(jbModificarTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTarjetasExistentes)
                .addGap(2, 2, 2)
                .addComponent(jbEliminarTarjeta)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAñadirTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAñadirTarjetaActionPerformed
        // TODO add your handling code here:
        JDCrearTarejeta jDCrearTarejeta = new JDCrearTarejeta(this, false);
        jDCrearTarejeta.setVisible(true);
    }//GEN-LAST:event_jbAñadirTarjetaActionPerformed

    private void jbModificarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbModificarTarjetaActionPerformed

    private void jbEliminarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEliminarTarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAñadirTarjeta;
    private javax.swing.JButton jbEliminarTarjeta;
    private javax.swing.JButton jbModificarTarjeta;
    private javax.swing.JLabel jlBienvenida;
    private javax.swing.JLabel jlTarjetasExistentes;
    private javax.swing.JLabel jlTotalGastado;
    // End of variables declaration//GEN-END:variables
}
