
import clases.TarjetaCredito;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author josemaria
 */
public class JFMenu extends javax.swing.JFrame {
    private static ArrayList<TarjetaCredito> tarjetasCreditos;

    /**
     * Creates new form JFMenu
     */
    public JFMenu() {
        initComponents();
        inicializar();
    }
    
    private void inicializar() {
        tarjetasCreditos = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlBienvenida = new javax.swing.JLabel();
        jbAñadirTarjeta = new javax.swing.JButton();
        jbModificarTarjeta = new javax.swing.JButton();
        jbEliminarTarjeta = new javax.swing.JButton();
        jlTotalGastado = new javax.swing.JLabel();
        jlTarjetasExistentes = new javax.swing.JLabel();
        jlTitularesActuales = new javax.swing.JLabel();
        jlTitularesActualesNombres = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlBienvenida.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jlBienvenida.setText("GESTION DE TARJETAS");

        jbAñadirTarjeta.setText("Crear Nueva");
        jbAñadirTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAñadirTarjetaActionPerformed(evt);
            }
        });

        jbModificarTarjeta.setText("Modificar Tarjeta");
        jbModificarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarTarjetaActionPerformed(evt);
            }
        });

        jbEliminarTarjeta.setText("Eliminar Tarjeta");
        jbEliminarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarTarjetaActionPerformed(evt);
            }
        });

        jlTotalGastado.setText("Total Gastado: 0");

        jlTarjetasExistentes.setText("Tarjetas Existentes: 0");

        jlTitularesActuales.setText("Titulares Actuales: ");

        jlTitularesActualesNombres.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbModificarTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbAñadirTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbEliminarTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jlBienvenida)))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlTotalGastado)
                            .addComponent(jlTarjetasExistentes)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlTitularesActualesNombres)
                                .addComponent(jlTitularesActuales)))))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jlBienvenida)
                .addGap(50, 50, 50)
                .addComponent(jbAñadirTarjeta)
                .addGap(4, 4, 4)
                .addComponent(jlTotalGastado)
                .addGap(8, 8, 8)
                .addComponent(jbModificarTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTarjetasExistentes)
                .addGap(2, 2, 2)
                .addComponent(jbEliminarTarjeta)
                .addGap(18, 18, 18)
                .addComponent(jlTitularesActuales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlTitularesActualesNombres)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAñadirTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAñadirTarjetaActionPerformed
        // TODO add your handling code here:
        JDCrearTarejeta jDCrearTarejeta = new JDCrearTarejeta(this, true);
        jDCrearTarejeta.setVisible(true);
        
        if (jDCrearTarejeta.isCreada()) {
            tarjetasCreditos.add(jDCrearTarejeta.getTarjetaCredito());
            actualizarTotalGastadoTextLabel();
            actualizarTarjetasExistentesTextLabel();
            actualizarTitularTextLabel();
            jbEliminarTarjeta.setVisible(true);
        }
    }//GEN-LAST:event_jbAñadirTarjetaActionPerformed

    private void jbModificarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarTarjetaActionPerformed
        if (tarjetasCreditos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existen Tarjetas", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            ArrayList<String> validNifs = new ArrayList<>();
            for (TarjetaCredito tarjeta : tarjetasCreditos) {
                validNifs.add(tarjeta.getNif());
            }
            JDValidarNIF jDValidarNIF = new JDValidarNIF(this, true);
            jDValidarNIF.setValidNIF(validNifs);
            jDValidarNIF.setVisible(true);
            int tarjetaIndex = jDValidarNIF.getIndexNIF();
            if (tarjetaIndex != -1) {
                TarjetaCredito tarjetaSeleccionada = tarjetasCreditos.get(tarjetaIndex);
                JDTarjeta jDTarjeta = new JDTarjeta(this, true, tarjetaSeleccionada);
                jDTarjeta.setVisible(true);
            }
            
        }
    }//GEN-LAST:event_jbModificarTarjetaActionPerformed

    private void jbEliminarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarTarjetaActionPerformed
        if (tarjetasCreditos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existen Tarjetas", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            JDEliminarTarjeta jDEliminarTarjeta = new JDEliminarTarjeta(this, true, tarjetasCreditos);
            jDEliminarTarjeta.setVisible(true);
            if (jDEliminarTarjeta.isEliminado()) {
                actualizarTotalGastadoTextLabel();
                actualizarTarjetasExistentesTextLabel();
                actualizarTitularTextLabel();
            }
        }
        
    }//GEN-LAST:event_jbEliminarTarjetaActionPerformed

    private void actualizarTitularTextLabel() {
        StringBuilder titulares = new StringBuilder();
        tarjetasCreditos.forEach(tarjeta -> titulares.append(tarjeta.getTitular()+"\n"));
        jlTitularesActualesNombres.setText("<html>"+titulares+"</html>");
        jlTitularesActuales.setVisible(true);
    }
    private void actualizarTotalGastadoTextLabel() {
        int totalGastado = 0;
        for (TarjetaCredito tarjeta : tarjetasCreditos) {
            totalGastado += tarjeta.gastado();
        }
        jlTotalGastado.setText("Total Gastado: "+totalGastado);
        jlTotalGastado.setVisible(true);
    }
    
   private void actualizarTarjetasExistentesTextLabel() {
        jlTarjetasExistentes.setText("Tarjetas Existentes: "+tarjetasCreditos.size());
        jlTarjetasExistentes.setVisible(true);
   }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAñadirTarjeta;
    private javax.swing.JButton jbEliminarTarjeta;
    private javax.swing.JButton jbModificarTarjeta;
    private javax.swing.JLabel jlBienvenida;
    private javax.swing.JLabel jlTarjetasExistentes;
    private javax.swing.JLabel jlTitularesActuales;
    private javax.swing.JLabel jlTitularesActualesNombres;
    private javax.swing.JLabel jlTotalGastado;
    // End of variables declaration//GEN-END:variables
}
