/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.event.MouseEvent;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import modelo.Cancion;
import modelo.ModeloListaCanciones;

/**
 *
 * @author deifont
 */
public class VentanaJTable extends javax.swing.JFrame {

    /**
     * Creates new form VentanaJTable
     */
    public VentanaJTable() {
        initComponents();
        // Creamos el Modelos de la Lista
        modelo = new ModeloListaCanciones();
        // Creamos una Canción
        Cancion c = new Cancion("Hola", "Titulo", 214);
        // Añadimos la Canción
        modelo.añadirCancion(c); 
        // Creamos una nueva Canción
        c = new Cancion("Segunda cancion", "Titulo 2", 111);
        
        // Añadimos la Canción
        modelo.añadirCancion(c);
        // Actualizamos JTable para que use el Modelo de Canción
        jtListaCanciones.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuEliminarCancion = new javax.swing.JPopupMenu();
        jmEliminarCancion = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaCanciones = new javax.swing.JTable();
        jmMenuPrincipal = new javax.swing.JMenuBar();
        jmCancion = new javax.swing.JMenu();
        jmAñadirCancion = new javax.swing.JMenuItem();

        jPopupMenuEliminarCancion.setToolTipText("");

        jmEliminarCancion.setText("Eliminar");
        jmEliminarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEliminarCancionActionPerformed(evt);
            }
        });
        jPopupMenuEliminarCancion.add(jmEliminarCancion);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtListaCanciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Identificador", "Nombre", "Apellidos", "Dirección"
            }
        ));
        jtListaCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListaCancionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListaCanciones);

        jmCancion.setText("Cancion");

        jmAñadirCancion.setText("Añadir");
        jmAñadirCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAñadirCancionActionPerformed(evt);
            }
        });
        jmCancion.add(jmAñadirCancion);

        jmMenuPrincipal.add(jmCancion);

        setJMenuBar(jmMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAñadirCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAñadirCancionActionPerformed
        JDCancion jDNuevaCancion = new JDCancion(this,true);
        jDNuevaCancion.setVisible(true);
        
        if (jDNuevaCancion.isAceptada()) {
            Cancion nuevaCancion = jDNuevaCancion.getCancion();
            modelo.añadirCancion(nuevaCancion);
        }
    }//GEN-LAST:event_jmAñadirCancionActionPerformed

    /**
     * Evento que controla cuando se realiza click Sobre los Elemento JTable.
     * Controla el doble Click y el Click Derecho.
     * El doble Click muestra un JDialog para modificar la información de la Canción.
     * Click Derecho muestra un Menu para eliminar la canción seleccionada.
     * @param evt 
     */
    private void jtListaCancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListaCancionesMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) { // Si es Click Derecho
            // Mostramos  el Menú
            jPopupMenuEliminarCancion.show(jtListaCanciones, evt.getX(), evt.getY());
        } else if (evt.getClickCount() == 2) { // Si ha realizado Dos Clicks
            int index = jtListaCanciones.getSelectedRow(); // Obtenemos el indice de la canción seleccionada (JTable)
            JDCancion jdCancion = new JDCancion(this, true); // Creamos el JDialog para modificar la Canción
            Cancion cancionAModificar = modelo.getCancion(index); //Obtenemos la Canción seleccionada por el Usuario
            jdCancion.setNombreCancion(cancionAModificar.getNombre()); // Insertamos en el JDialog el Nombre de la Canción
            jdCancion.setAutorCancion(cancionAModificar.getAutor()); // Insertamos en el JDialog el Autor de la Canción
            jdCancion.setDuracionCancion(cancionAModificar.getDuracion()); // Insetamos en el JDialog la Duracion de la Canción
            jdCancion.setVisible(true); // Hacemos Visible el JDialog
            
            if (jdCancion.isAceptada()) { // Si la película ha sido aceptada
                Cancion cancionModificada = jdCancion.getCancion(); // Obteneos la canción modificada
                modelo.setNombre(index,cancionModificada.getNombre()); // Modificamos el Nombre
                modelo.setAutor(index, cancionModificada.getAutor()); // Modificamos el Autor
                modelo.setDuracion(index, cancionModificada.getDuracion()); // Modificamos la Duración
                modelo.fireTableRowsUpdated(index, index);
            }
        }
    }//GEN-LAST:event_jtListaCancionesMouseClicked

    private void jmEliminarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEliminarCancionActionPerformed
        int index = jtListaCanciones.getSelectedRow(); // Obtenemos el indice de la canción seleccionada
        if (modelo.eliminarCancion(index)) { // Si se ha podido eliminar
            modelo.fireTableDataChanged(); // Actualizamos el JTable
        }
    }//GEN-LAST:event_jmEliminarCancionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJTable().setVisible(true);
            }
        });
    }

    private ModeloListaCanciones modelo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenuEliminarCancion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmAñadirCancion;
    private javax.swing.JMenu jmCancion;
    private javax.swing.JMenuItem jmEliminarCancion;
    private javax.swing.JMenuBar jmMenuPrincipal;
    private javax.swing.JTable jtListaCanciones;
    // End of variables declaration//GEN-END:variables
}
