/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

import Funciones.Utilities;
import java.awt.Dialog;
import java.awt.event.MouseEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.Capitulo;
import modelo.ModeloListaCapitulo;
import modelo.Serie;
import modelo.Temporada;

/**
 *
 * @author josemaria
 */
public class JDGestionarTemporada extends javax.swing.JDialog {

    /**
     * Creates new form JDGestionarTemporada
     */
    public JDGestionarTemporada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JDGestionarTemporada(Dialog parent, boolean modal, Serie serie, int indiceTemporada) {
        super(parent,modal);
        initComponents();
        this.serieSeleccionada = serie;
        this.temporadaSeleccionada = serie.getCopiaTemporada(indiceTemporada);
        this.indiceTemporada = indiceTemporada;
        inicializar();
    }
    
    private void inicializar() {
        modelo = new ModeloListaCapitulo();
        this.jtListaCapitulos.setModel(modelo);
        jlNombreTemporada.setText("Temporada "+(this.indiceTemporada+1));
        jtfFechaEstreno.setText(formato.format(serieSeleccionada.getCopiaTemporada(indiceTemporada).getFechaEstreno()));
        actualizarListaCapitulos();
    }
    
    public boolean isActualizado() {
        return this.isActualizado;
    }
    public Serie getSerie() {
        System.out.println(serieSeleccionada.getCopiaTemporada(indiceTemporada));
        return new Serie(serieSeleccionada);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmEliminarCapitulo = new javax.swing.JPopupMenu();
        jmiEliminarCapitulo = new javax.swing.JMenuItem();
        jlTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListaCapitulos = new javax.swing.JTable();
        jlNombreTemporada = new javax.swing.JLabel();
        jlTituloFechaEstreno = new javax.swing.JLabel();
        jtfFechaEstreno = new javax.swing.JTextField();
        jbActualizar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbCrearCapitulo = new javax.swing.JButton();

        jmiEliminarCapitulo.setText("Eliminar");
        jmiEliminarCapitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEliminarCapituloActionPerformed(evt);
            }
        });
        jpmEliminarCapitulo.add(jmiEliminarCapitulo);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlTitulo.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jlTitulo.setText("GESTIONAR TEMPORADA");

        jtListaCapitulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtListaCapitulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtListaCapitulosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtListaCapitulos);

        jlNombreTemporada.setText("jLabel1");

        jlTituloFechaEstreno.setText("Fecha Estreno:");

        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbCrearCapitulo.setText("Crear Capitulo");
        jbCrearCapitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearCapituloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlTitulo)
                .addGap(195, 195, 195))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlNombreTemporada)
                            .addComponent(jlTituloFechaEstreno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfFechaEstreno, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbCrearCapitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbCancelar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlNombreTemporada)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTituloFechaEstreno)
                            .addComponent(jtfFechaEstreno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jbCrearCapitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbActualizar)
                            .addComponent(jbCancelar))
                        .addGap(46, 46, 46))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.isActualizado = false;
        this.setVisible(false);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        boolean isValidInput = true;
        String fechaEstrenoString = jtfFechaEstreno.getText();
        
        if (!Utilities.validateLocalDate(fechaEstrenoString)) {
            JOptionPane.showMessageDialog(this, "La fecha de estreno es inválida", "Error", JOptionPane.ERROR_MESSAGE);
            isValidInput = false;
        }
        if (isValidInput && !Utilities.validateLocaDateIsAfterOrEquals(Utilities.convertToLocalDate(fechaEstrenoString), serieSeleccionada.getFechaEstreno())) {
            JOptionPane.showMessageDialog(this, "La fecha de estreno es anterior a la Fecha de Estreno de la Serie", "Error", JOptionPane.ERROR_MESSAGE);
            isValidInput = false;
        }
        
        if (isValidInput) {
            LocalDate fechaEstrenoTemporada = Utilities.convertToLocalDate(fechaEstrenoString);
            if (serieSeleccionada.setFechaEstrenoTemporada(this.indiceTemporada, fechaEstrenoTemporada)) {
                this.isActualizado = true;
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Ya existe una Temporada el mismo mes.");
            }
        }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbCrearCapituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearCapituloActionPerformed
        boolean isValido = true; 
        JTextField jtfTitulo = new JTextField();
        JTextField jtfFechaEmision = new JTextField();
        Object[] message = {
            "Titulo: ", jtfTitulo,
            "Fecha Emisión: ", jtfFechaEmision
        };
        
        int option = JOptionPane.showConfirmDialog(this, message, "Crear Capítulo", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            String titulo = jtfTitulo.getText();
            System.out.println(titulo);
            String fechaEmisionString= jtfFechaEmision.getText();
            if (titulo.isBlank()) {
                JOptionPane.showMessageDialog(this, "El Título no puede estar vacío");
                isValido = false;
            }
            if (isValido && !Utilities.validateLocalDate(fechaEmisionString)) {
                JOptionPane.showMessageDialog(this, "El formato de la Fecha de Emisión es erroneo debe de ser dd/mm/yyyy");
                isValido = false;
            }
            if (isValido && !Utilities.validateLocaDateIsAfterOrEquals(Utilities.convertToLocalDate(fechaEmisionString), temporadaSeleccionada.getFechaEstreno())) {
                JOptionPane.showMessageDialog(this, "La fecha insertada es anterior a la Fecha de Estreno de la Temporada");
                isValido = false;
            }
            
            if (isValido) {
                LocalDate fechaEmision = Utilities.convertToLocalDate(fechaEmisionString);
                Capitulo nuevoCapitulo = new Capitulo(titulo, fechaEmision);
                if (serieSeleccionada.añadirCapitulo(indiceTemporada, nuevoCapitulo)) {
                    JOptionPane.showMessageDialog(this, "Capítulo creado con exito");
                    this.isActualizado = true;
                    actualizarListaCapitulos();
                } else {
                    JOptionPane.showMessageDialog(this, "El capítulo ya exite en la Temporada");
                }
            }
        }
    }//GEN-LAST:event_jbCrearCapituloActionPerformed

    private void jtListaCapitulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListaCapitulosMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) { // Si es Click Derecho
            // Mostramos  el Menú
            jpmEliminarCapitulo.show(jtListaCapitulos, evt.getX(), evt.getY());
        } else if (evt.getClickCount() == 2) { // Si ha realizado Dos Clicks
            /*int index = jtListaTemporadas.getSelectedRow(); // Obtenemos el indice de la temporada seleccionada (JTable)
            Serie copiaSerie = new Serie(serieSeleccionada);
            JDGestionarTemporada jDGestionarTemporada = new JDGestionarTemporada(this, true, copiaSerie, index);
            jDGestionarTemporada.setVisible(true);
            
            if (jDGestionarTemporada.isActualizado()) {
                Serie serieModificada = jDGestionarTemporada.getSerie();
                serieSeleccionada = new Serie(serieModificada);
                this.isActualizada = true;
                actualizarTablaTemporadas();
            }*/
        }
    }//GEN-LAST:event_jtListaCapitulosMouseClicked

    private void jmiEliminarCapituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEliminarCapituloActionPerformed
        int index = jtListaCapitulos.getSelectedRow();
        if (index != -1) {
            Capitulo capituloSeleccionado = temporadaSeleccionada.getCapitulo(index);
            serieSeleccionada.eliminarCapitulo(indiceTemporada, capituloSeleccionado.getTitulo());
            modelo.eliminarCapitulo(capituloSeleccionado);
        }
        
    }//GEN-LAST:event_jmiEliminarCapituloActionPerformed

   
    private void actualizarListaCapitulos() {
        modelo.eliminarTodo();
        Temporada temporada = serieSeleccionada.getCopiaTemporada(indiceTemporada);
        int contador = 0;
        Capitulo capitulo = temporada.getCapitulo(contador++);
        while (capitulo != null) {
            modelo.añadirCapitulo(capitulo);
            capitulo = temporada.getCapitulo(contador++);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDGestionarTemporada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDGestionarTemporada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDGestionarTemporada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDGestionarTemporada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDGestionarTemporada dialog = new JDGestionarTemporada(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    
    private static DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy"); // Definir el formato deseado
    private boolean isActualizado;
    private Serie serieSeleccionada;
    private Temporada temporadaSeleccionada;
    private int indiceTemporada;
    private ModeloListaCapitulo modelo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbCrearCapitulo;
    private javax.swing.JLabel jlNombreTemporada;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlTituloFechaEstreno;
    private javax.swing.JMenuItem jmiEliminarCapitulo;
    private javax.swing.JPopupMenu jpmEliminarCapitulo;
    private javax.swing.JTable jtListaCapitulos;
    private javax.swing.JTextField jtfFechaEstreno;
    // End of variables declaration//GEN-END:variables
}
